url = "https://crates.io"
name = "crates.io"
cron = "0   *   *     *       *  *  *"
window_width = 1280
window_height = 1024
step_timeout = 15000
step_interval = 1000
retry = [ 60, 300, 600 ]

# wait before page is ready
[[steps]]
kind = "wait"
exec = """document.querySelector("div[class*='stats'] span[class*='value']") ? true : false"""

# downloads
[[steps]]
kind = "value"
key = "downloads"
exec = """(() => {
    const el = document.querySelectorAll("div[class*='stats'] span[class*='value']")[0];

    // red border
    el.parentNode.style.borderColor = "red";
    el.parentNode.style.borderStyle = "solid";

    return parseInt(el.textContent.split(',').join(''));
})()"""

    [[steps.levels]]
    name = "green"
    more = 1

# crates 
[[steps]]
kind = "value"
key = "crates"
exec = """(() => {
    const el = document.querySelectorAll("div[class*='stats'] span[class*='value']")[1];

    // red border
    el.parentNode.style.borderColor = "red";
    el.parentNode.style.borderStyle = "solid";

    return parseInt(el.textContent.split(',').join(''));
})()"""

    [[steps.levels]]
    name = "green"
    more = 1


# take screenshot
[[steps]]
kind = "screenshot"
key = "stats"
