url = "https://github.com/estin/cywad"
name = "cywad github"
cron = "0   *   *     *       *  *  *"
window_width = 1280
window_height = 1024
step_timeout = 15000
step_interval = 1000
retry = [ 60, 300, 600 ]

# wait before page is ready
[[steps]]
kind = "wait"
exec = """document.querySelector("a.js-social-count") ? true : false"""

# get count of stars
[[steps]]
kind = "value"
key = "stars"
exec = """(() => {
    const el = document.querySelector("a.js-social-count");

    // red border
    el.parentNode.style.borderColor = "red";
    el.parentNode.style.borderStyle = "solid";

    return parseInt(el.innerHTML);
})()"""

    [[steps.levels]]
    name = "green"
    more = 50

    [[steps.levels]]
    name = "red"
    less = 10

    [[steps.levels]]
    name = "yellow"
    less = 50


# take screenshot
[[steps]]
kind = "screenshot"
key = "stars"
