url = "https://github.com/estin/cywad"
name = "cywad github"
cron = "0   *   *     *       *  *  *"
window_width = 1280
window_height = 1024
step_timeout = 15000
step_interval = 1000
retry = [ 60, 300, 600 ]

# wait before page is ready
[[steps]]
kind = "wait"
exec = """document.querySelector("div.repohead a[aria-label*='starred']") ? true : false"""

# get count of stars
[[steps]]
kind = "value"
key = "stars"
exec = """(() => {
    const el = document.querySelector("div.repohead a[aria-label*='starred']");

    // red border
    el.parentNode.style.borderColor = "red";
    el.parentNode.style.borderStyle = "solid";

    return parseInt(el.getAttribute("aria-label").split(' ')[0]);
})()"""

    [[steps.levels]]
    name = "green"
    more = 50

    [[steps.levels]]
    name = "red"
    less = 10

    [[steps.levels]]
    name = "yellow"
    less = 50


# get count of issues
[[steps]]
kind = "value"
key = "issues"
exec = """(() => {
    const el = document.querySelector("a[data-selected-links^='repo_issues'] span.Counter");

    // red border
    el.parentNode.style.borderColor = "red";
    el.parentNode.style.borderStyle = "solid";

    return parseInt(el.textContent);
})()"""

    [[steps.levels]]
    name = "green"
    less = 3

    [[steps.levels]]
    name = "yellow"
    less = 5

    [[steps.levels]]
    name = "red"
    more = 5

# get count of Pull Requests
[[steps]]
kind = "value"
key = "PRs"
exec = """(() => {
    const el = document.querySelector("a[data-selected-links^='repo_pulls'] span.Counter");

    // red border
    el.parentNode.style.borderColor = "red";
    el.parentNode.style.borderStyle = "solid";

    return parseInt(el.textContent);
})()"""

    [[steps.levels]]
    name = "green"
    more = 1


# take screenshot
[[steps]]
kind = "screenshot"
key = "stars"
